In [37]:
import pandas as pd

df_val = pd.read_csv("..\data\dataset_txt_only_False_embeddings_True_val.zip")
df_train = pd.read_csv("..\data\dataset_txt_only_False_embeddings_True_train.zip")
df_effects = pd.read_csv(r"..\output\04_evaluation\sorted_effects.csv")

df_full = pd.concat([df_val, df_train], ignore_index=True)
df_full.head()

,ASIN,date,index,Q_t,PRICE,P_bb_t,text,window,REVIEW_COUNT,RATING,...,Delta_Q_t,Delta_P_bb_t,pred_ml_l,pred_ml_m,pred_ml_l_diff,pred_ml_m_diff,pred_ml_l_lag_1,pred_ml_m_lag_1,pred_ml_l_diff_lag_1,pred_ml_m_diff_lag_1
0,1947494961,2023-01-30,1,-10.685092,3.068750,3.318075,Gale Force Nine - Aliens: Another Glorious Day...,28.0,1501.214286,4.700000,...,NaN,NaN,-10.608895,2.811658,NaN,NaN,NaN,NaN,NaN,NaN
1,1947494961,2023-02-27,9,-10.728496,3.149694,3.435898,Gale Force Nine - Aliens: Another Glorious Day...,28.0,1552.535714,4.700000,...,-0.043404,0.117823,-10.608895,2.811658,-0.060465,-0.003964,-10.849645,2.824807,-0.032787,-0.013729
2,1947494961,2023-03-27,17,-11.041387,3.201483,3.457206,Gale Force Nine - Aliens: Another Glorious Day...,28.0,1567.000000,4.700000,...,-0.312891,0.021309,-10.608895,2.811658,0.000150,-0.002530,-10.825026,2.825181,0.138726,-0.013659
3,1947494961,2023-04-24,25,-11.055897,3.357830,3.425530,Gale Force Nine - Aliens: Another Glorious Day...,28.0,1517.714286,4.666667,...,-0.014510,-0.031676,-10.608895,2.811658,-0.011212,-0.002330,-10.818141,2.825185,0.028958,-0.008854
4,1947494961,2023-05-22,33,-11.157410,3.330417,3.375880,Gale Force Nine - Aliens: Another Glorious Day...,28.0,1580.500000,4.600000,...,-0.101513,-0.049650,-10.608895,2.811658,-0.031883,-0.002634,-10.831144,2.824067,0.021158,-0.010682

In [30]:
df_effects

                  date  SortEff_lin  SortEff_tab_dml  SortEff_deep_dml
ASIN
1947494961  2023-02-27    -0.717623        -0.737958         -0.817810
1947494961  2023-03-27    -0.714928        -0.736624         -0.816437
1947494961  2023-04-24    -0.677495        -0.694652         -0.740304
1947494961  2023-05-22    -0.674952        -0.691325         -0.734252
1947494961  2023-06-19    -0.661135        -0.675017         -0.705447
...                ...          ...              ...               ...
B0CPSR7XM1  2024-01-29    -0.660896        -0.663711         -0.801973
B0CQ1SLW1P  2024-01-29    -0.434598        -0.452333         -0.398493
B0CQ1XKDQX  2024-01-29    -0.468150        -0.487765         -0.470218
B0CQWJ3247  2024-01-29    -0.763602        -0.802300         -0.856356
B0CQWJZGSY  2024-01-29    -0.744686        -0.779838         -0.776863

[38041 rows x 4 columns]

In [33]:
df_val.set_index(["ASIN", "date"]).join(df_effects.set_index(["ASIN", "date"]), how="left")

                        index        Q_t     PRICE    P_bb_t  \
ASIN       date
1947494961 2023-01-30       1 -10.685092  3.068750  3.318075
           2023-02-27       9 -10.728496  3.149694  3.435898
           2023-03-27      17 -11.041387  3.201483  3.457206
           2023-04-24      25 -11.055897  3.357830  3.425530
           2023-05-22      33 -11.157410  3.330417  3.375880
...                       ...        ...       ...       ...
B0CQWJ3247 2024-01-01  592585  -9.410761  2.078191  2.078191
           2024-01-29  592593  -9.367674  2.116772  2.116772
B0CQWJZGSY 2024-01-01  592741  -9.376208  1.885553  1.885553
           2024-01-29  592749  -9.461319  1.998193  1.998193
B0CRDLRP38 2024-01-29  592905 -11.850726  3.295466  3.295466

                                                                    text  \
ASIN       date
1947494961 2023-01-30  Gale Force Nine - Aliens: Another Glorious Day...
           2023-02-27  Gale Force Nine - Aliens: Another Glorious Day...
           2023-03-27  Gale Force Nine - Aliens: Another Glorious Day...
           2023-04-24  Gale Force Nine - Aliens: Another Glorious Day...
           2023-05-22  Gale Force Nine - Aliens: Another Glorious Day...
...                                                                  ...
B0CQWJ3247 2024-01-01  Car Toys Diecast 1:55 Metal Model Vehical Toy ...
           2024-01-29  Car Toys Diecast 1:55 Metal Model Vehical Toy ...
B0CQWJZGSY 2024-01-01  Car Toys Diecast 1:55 Metal Model Vehical Toy ...
           2024-01-29  Car Toys Diecast 1:55 Metal Model Vehical Toy ...
B0CRDLRP38 2024-01-29  Keejoy 2-in-1 Dinosaur Truck Toy with 6 Stylis...

                       window  REVIEW_COUNT    RATING  \
ASIN       date
1947494961 2023-01-30    28.0   1501.214286  4.700000
           2023-02-27    28.0   1552.535714  4.700000
           2023-03-27    28.0   1567.000000  4.700000
           2023-04-24    28.0   1517.714286  4.666667
           2023-05-22    28.0   1580.500000  4.600000
...                       ...           ...       ...
B0CQWJ3247 2024-01-01    28.0      3.000000  3.500000
           2024-01-29    28.0      2.357143  3.982143
B0CQWJZGSY 2024-01-01    28.0      3.000000  3.500000
           2024-01-29    28.0      2.357143  3.982143
B0CRDLRP38 2024-01-29    28.0     11.166667  3.708696

                       New Offer Count: Current  \
ASIN       date
1947494961 2023-01-30                         2
           2023-02-27                         2
           2023-03-27                         2
           2023-04-24                         2
           2023-05-22                         2
...                                         ...
B0CQWJ3247 2024-01-01                         1
           2024-01-29                         1
B0CQWJZGSY 2024-01-01                         1
           2024-01-29                         1
B0CRDLRP38 2024-01-29                         1

                       Count of retrieved live offers: New, FBA  ...  \
ASIN       date                                                  ...
1947494961 2023-01-30                                         1  ...
           2023-02-27                                         1  ...
           2023-03-27                                         1  ...
           2023-04-24                                         1  ...
           2023-05-22                                         1  ...
...                                                         ...  ...
B0CQWJ3247 2024-01-01                                         0  ...
           2024-01-29                                         0  ...
B0CQWJZGSY 2024-01-01                                         0  ...
           2024-01-29                                         0  ...
B0CRDLRP38 2024-01-29                                         1  ...

                       pred_ml_m  pred_ml_l_diff  pred_ml_m_diff  \
ASIN       date
1947494961 2023-01-30   2.811658             NaN             NaN
           2023-02-27   2.811658       -0.060465       -0.003964
           2023-03-27   2.811658        0.000150       -0.002530
           2023-04-24   2.811658       -0.011212       -0.002330
           2023-05-22   2.811658       -0.031883       -0.002634
...                          ...             ...             ...
B0CQWJ3247 2024-01-01   2.178872             NaN             NaN
           2024-01-29   2.178872       -0.379038       -0.003218
B0CQWJZGSY 2024-01-01   2.278417             NaN             NaN
           2024-01-29   2.278417       -0.152477       -0.001815
B0CRDLRP38 2024-01-29   3.287715             NaN             NaN

                      pred_ml_l_lag_1  pred_ml_m_lag_1  pred_ml_l_diff_lag_1  \
ASIN       date
1947494961 2023-01-30             NaN              NaN                   NaN
           2023-02-27      -10.849645         2.824807             -0.032787
           2023-03-27      -10.825026         2.825181              0.138726
           2023-04-24      -10.818141         2.825185              0.028958
           2023-05-22      -10.831144         2.824067              0.021158
...                               ...              ...                   ...
B0CQWJ3247 2024-01-01             NaN              NaN                   NaN
           2024-01-29       -9.640119         2.161365              0.403997
B0CQWJZGSY 2024-01-01             NaN              NaN                   NaN
           2024-01-29       -9.847777         2.264066             -0.058069
B0CRDLRP38 2024-01-29             NaN              NaN                   NaN

                       pred_ml_m_diff_lag_1  SortEff_lin  SortEff_tab_dml  \
ASIN       date
1947494961 2023-01-30                   NaN          NaN              NaN
           2023-02-27             -0.013729    -0.717623        -0.737958
           2023-03-27             -0.013659    -0.714928        -0.736624
           2023-04-24             -0.008854    -0.677495        -0.694652
           2023-05-22             -0.010682    -0.674952        -0.691325
...                                     ...          ...              ...
B0CQWJ3247 2024-01-01                   NaN          NaN              NaN
           2024-01-29             -0.005658    -0.763602        -0.802300
B0CQWJZGSY 2024-01-01                   NaN          NaN              NaN
           2024-01-29             -0.004463    -0.744686        -0.779838
B0CRDLRP38 2024-01-29                   NaN          NaN              NaN

                       SortEff_deep_dml
ASIN       date
1947494961 2023-01-30               NaN
           2023-02-27         -0.817810
           2023-03-27         -0.816437
           2023-04-24         -0.740304
           2023-05-22         -0.734252
...                                 ...
B0CQWJ3247 2024-01-01               NaN
           2024-01-29         -0.856356
B0CQWJZGSY 2024-01-01               NaN
           2024-01-29         -0.776863
B0CRDLRP38 2024-01-29               NaN

[41832 rows x 349 columns]

In [34]:
sim_cols = [
 'similarity_cluster_0',
 'similarity_cluster_1',
 'similarity_cluster_2',
 'similarity_cluster_3',
 'similarity_cluster_4',
]

In [39]:
# assign cluster label for each row based on the highest similarity score in sim_cols

df_full['cluster_label'] = df_full[sim_cols].idxmax(axis=1)
df_full['cluster_label'] = df_full['cluster_label'].str.replace('similarity_cluster_', '').astype(int)
df_full.head()

,ASIN,date,index,Q_t,PRICE,P_bb_t,text,window,REVIEW_COUNT,RATING,...,Delta_P_bb_t,pred_ml_l,pred_ml_m,pred_ml_l_diff,pred_ml_m_diff,pred_ml_l_lag_1,pred_ml_m_lag_1,pred_ml_l_diff_lag_1,pred_ml_m_diff_lag_1,cluster_label
0,1947494961,2023-01-30,1,-10.685092,3.068750,3.318075,Gale Force Nine - Aliens: Another Glorious Day...,28.0,1501.214286,4.700000,...,NaN,-10.608895,2.811658,NaN,NaN,NaN,NaN,NaN,NaN,2
1,1947494961,2023-02-27,9,-10.728496,3.149694,3.435898,Gale Force Nine - Aliens: Another Glorious Day...,28.0,1552.535714,4.700000,...,0.117823,-10.608895,2.811658,-0.060465,-0.003964,-10.849645,2.824807,-0.032787,-0.013729,2
2,1947494961,2023-03-27,17,-11.041387,3.201483,3.457206,Gale Force Nine - Aliens: Another Glorious Day...,28.0,1567.000000,4.700000,...,0.021309,-10.608895,2.811658,0.000150,-0.002530,-10.825026,2.825181,0.138726,-0.013659,2
3,1947494961,2023-04-24,25,-11.055897,3.357830,3.425530,Gale Force Nine - Aliens: Another Glorious Day...,28.0,1517.714286,4.666667,...,-0.031676,-10.608895,2.811658,-0.011212,-0.002330,-10.818141,2.825185,0.028958,-0.008854,2
4,1947494961,2023-05-22,33,-11.157410,3.330417,3.375880,Gale Force Nine - Aliens: Another Glorious Day...,28.0,1580.500000,4.600000,...,-0.049650,-10.608895,2.811658,-0.031883,-0.002634,-10.831144,2.824067,0.021158,-0.010682,2

In [44]:
import os

# Short labels from the LLM headline exercise (used as readable cluster names)
cluster_headlines_short = {
    0: "Movie-Themed Collectibles",
    1: "Large-Scale Utility Trucks",
    2: "1:64 Die-Cast Replicas",
    3: "Pull-Back Models & Wooden Trains",
    4: "Stunt Vehicles & Playsets",
}


# ── Load per-observation deep-DML elasticity and merge on (ASIN, date) ──────
sorted_eff = pd.read_csv("../output/04_evaluation/sorted_effects.csv")
sorted_eff["date"] = sorted_eff["date"].astype(str)
df_full["date"] = df_full["date"].astype(str)

df_char = df_full.merge(
    sorted_eff[["ASIN", "date", "SortEff_deep_dml"]],
    on=["ASIN", "date"],
    how="left",
)

# ── Build per-cluster statistics ─────────────────────────────────────────────
rows = []
for c in range(5):
    sub = df_char[df_char["cluster_label"] == c]
    sub_asin = sub.groupby("ASIN").first().reset_index()  # one row per product

    n_prod         = int(sub["ASIN"].nunique())
    n_obs          = len(sub)
    mean_price     = sub["P_bb_t"].mean()
    mean_rating    = sub["RATING"].mean()
    # Product-level median review count (avoids repeating the same product
    # across many time periods inflating the statistic)
    median_reviews = int(sub_asin["REVIEW_COUNT"].median())

    # Top-2 subcategories by number of distinct products
    top_cats = (
        sub_asin["subcat_aggregated"]
        .value_counts()
        .head(2)
        .index.tolist()
    )
    cat_str = " / ".join(top_cats)

    # Mean elasticity (observations matched to sorted_effects only)
    mean_elas = sub["SortEff_deep_dml"].mean()

    rows.append(
        {
            "Cluster": c,
            "Label": cluster_headlines_short[c],
            "# Products": n_prod,
            "# Observations": n_obs,
            "Mean Price ($)": round(mean_price, 2),
            "Mean Rating": round(mean_rating, 2),
            "Median Reviews": median_reviews,
            "Dominant Product Type": cat_str,
            "Mean Elasticity": round(mean_elas, 3),
        }
    )

df_summary = pd.DataFrame(rows).set_index("Cluster")

# ── Save ─────────────────────────────────────────────────────────────────────
df_summary.to_csv(os.path.join("..\output\R2", "cluster_summary_table.csv"))

# ── Display ──────────────────────────────────────────────────────────────────
df_summary.style.format(
    {
        "Mean Price ($)": "${:.2f}",
        "Mean Rating": "{:.2f}",
        "Mean Elasticity": "{:.3f}",
    }
)